
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:15.1
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${DATABASE_NAME:-app}"
      MYSQL_USER: "${DATABASE_USER:-app}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD:-app}"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./var/mysql:/var/www/var
    networks:
      - app-network

  adminer:
    image: adminer:latest
    depends_on:
      - database
    environment:
      - APP_ENV: dev
    ports:
      - "8082:8080"
    networks:
      - app-network

  mailer:
      image: axllent/mailpit
      ports:
        - "1025:1025"
        - "8025:8025"
      environment:
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
        
      networks:
        - app-network

networks:
  app-network:

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
