services:
  database:
    image: mysql:${DATABASE_VERSION:-8.0}
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${DATABASE_NAME:-app}"
      MYSQL_USER: "${DATABASE_USER:-app}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD:-app}"
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
    restart: unless-stopped

  mailer:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    restart: unless-stopped

  app:
    build:
      dockerfile: Dockerfile
      # image: app:latest     # ← garde l’un OU l’autre
    ports:
      - "8080:80"
    environment:
      APP_ENV: "${APP_ENV:-dev}"
      LOAD_FIXTURES: "${LOAD_FIXTURES:-true}"
      DATABASE_URL: "mysql://${DATABASE_USER:-app}:${DATABASE_PASSWORD:-app}@database:3306/${DATABASE_NAME:-app}?serverVersion=${DATABASE_SERVER_VERSION:-8.0.32}&charset=utf8mb4"
      MAILER_DSN: "smtp://mailer:1025"
    depends_on:
      database:
        condition: service_healthy
      mailer:
        condition: service_started
    restart: unless-stopped

volumes:
  database_data:
