services:
  database:
    image: mysql:${DATABASE_VERSION:-8.0}
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${DATABASE_NAME:-app}"
      MYSQL_USER: "${DATABASE_USER:-app}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD:-app}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./var/mysql:/var/www/var
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  app:
    build:
        dockerfile: Dockerfile
    image: app
    ports:
      - "8080:80"
    environment:
      APP_ENV: "${APP_ENV:-dev}"
      DATABASE_URL: "mysql://${DATABASE_USER:-app}:${DATABASE_PASSWORD:-app}@database:3306/${DATABASE_NAME:-app}"
      MAILER_DSN: "smtp://mailer:1025"
    depends_on:
      - database
      - mailer

volumes:
  database_data:
